apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen-coder-14b
  namespace: rhoai-models
  labels:
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/part-of: code-assistant-lab
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    openshift.io/display-name: "Qwen2.5-Coder-14B-Instruct (FP8)"
spec:
  predictor:
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      storageUri: hf://RedHatAI/Qwen2.5-Coder-14B-Instruct-FP8-dynamic
      args:
        - --max-model-len=8192
      resources:
        requests:
          cpu: "4"
          memory: 24Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
